### ISSUE TITLE
Bug in translation

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#37]
```
python -m csp ../../../../../../../../../../programs/encodings/flow_shop/encoding.clingcon4 --stats=2 --quiet=1,0 ../../../../../../../../../../newbenchmarks/instances/flow_shop/tai20_10_1.lp
csp version 1.0
Reading from ...encodings/flow_shop/encoding.clingcon4 ...
*** ERROR: (csp): <application>: error: error during main:
  Traceback (most recent call last):
    File "/home/ostrowsk/miniconda3/envs/pyclingcon-ec2e3b0/lib/python3.7/site-packages/csp-0.1-py3.7.egg/csp/__main__.py", line 89, in main
    for model in prg.solve(on_statistics=self._on_statistics, yield_=True):
  RuntimeError: Propagator::init: error: error during initialization:
  Traceback (most recent call last):
    File "/home/ostrowsk/miniconda3/envs/pyclingcon-ec2e3b0/lib/python3.7/site-packages/csp-0.1-py3.7.egg/csp/__init__.py", line 57, in wrapper
    ret = func(self, *args, **kwargs)
    File "/home/ostrowsk/miniconda3/envs/pyclingcon-ec2e3b0/lib/python3.7/site-packages/csp-0.1-py3.7.egg/csp/__init__.py", line 2273, in init
    ret, rem = master.constraint_state(c).translate(cc, master)
  TypeError: cannot unpack non-iterable bool object
```

[encoding.clingcon4.txt](https://github.com/MaxOstrowski/clingo/files/4164793/encoding.clingcon4.txt)
[tai20_10_1.lp.txt](https://github.com/MaxOstrowski/clingo/files/4164795/tai20_10_1.lp.txt)

**Comment by rkaminsk** [comment]
Just take the commit following in the log. This was just a wrong return, I already fixed yesterday.

c9e17cd8b15e94acb66b12053c75be5af18629d2

**Comment by rkaminsk** [comment]
Btw. this means that variables in the tai instances have very large bounds because they are not translated.
